---
title: Hubofcode
timezone: UTC
collections:
  machine-learning:
    title: Machine Learning
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: HubofCode
author: Samuel James
description: My personal blog on software engineering & machine learning
avatar: "/images/logo.png"
permalink: pretty
paginate: 15
excerpt_separator: "\n\n"
footer-links:
  dribbble: 
  email: samuel4abiodun@gmail.com
  facebook: 
  flickr: 
  github: abiodunjames
  instagram: 
  linkedin: samuel-james-abiodun
  pinterest: 
  rss: rss
  twitter: samueljabiodun
  stackoverflow: 
  youtube: 
  googleplus: 
  playconsole: 
disqus: samuelabiodun
google_analytics: UA-108117283-1
url: https://hubofco.de
enforce_ssl: https://hubofco.de
baseurl: "/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jemoji
- jekyll-remote-theme
- jekyll-twitter-plugin
include:
- _pages
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
